### ISSUE TITLE
WebGL MQTT Connectivity

### ISSUE THREAD

**Issue by Kirch21x** [jensandersson/jens-race#1]
Are you able connect to and MQTT broker through a WebGL build?  I tried this and am getting the following error in the browser console:

```
blob:http://10.52.82…a93e-5adb0c09ee7a:2 SocketException: Success

Rethrow as MqttConnectionException: Exception connecting to the broker

 
(Filename: currently not available on il2cpp Line: -1)
```

I am able to receive MQTT messages in unity play mode.

Any feedback would be great, thanks!

**Comment by jensandersson** [comment]
Hello! I have not tried a WebGL build, but I would guess you get blocked by browser CORS rules, because your MQTT broker is on a different host and port than the server where your game is hosted? You say it works in Unity play mode. I assume it also works when built as a standalone native game for your platform? I think you need to use MQTT over websockets -- there seems to be a non-Unity example of that at https://github.com/tanzilli/TanzoWings but I don't understand Italian. :-) However, in Unity it might not be possible (not in the same way, at least). https://docs.unity3d.com/Manual/webgl-networking.html seems to indicate that raw networking is simply disabled.

If you find out anything more about, please let me know!

**Comment by jensandersson** [comment]
Actually, when surfing for it now, I found http://unity3dassets.com/demos/wak-mqtt-demo1/index.html which at least appears to be MQTT from WebGL, and that led me to their asset store entry at https://www.assetstore.unity3d.com/en/?stay#!content/19663 which in turn had a link to their docs at http://unity3dassets.com/category/wak/ where I found http://unity3dassets.com/wak-mqtt-for-iot-brief-documentation/ . However, that requires their $49 SDK from the asset store, and I have no idea if it actually works.

If you investigate it further, or even try purchasing it, I am very curious how it went!

**Comment by Kirch21x** [comment]
I purchased the asset you linked and was able to get it up and running after some help from the developer.  He was extremely helpful.  You are correct about the web sockets, that is how the asset works in combination with m2mqtt.

**Comment by jensandersson** [comment]
Happy to hear that! If your source code is public, or if it is not too much work to describe what you did, feel free to share it. In any case, I'll close this ticket soon.
